name: Morse 😺

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Verify TypeScript code
        run: npx tsc
      - name: Lint TypeScript code
        run: npx @biomejs/biome check src/lib.js
